pipeline:
  identifier: Build_Tabbukhan_css_project_1756380589809
  name: Build css-project
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Tabbukhan/css-project
  stages:
    - parallel:
        - stage:
            identifier: build
            name: build
            spec:
              caching:
                enabled: true
              cloneCodebase: true
              execution:
                steps:
                  - step:
                      identifier: echo
                      name: echo
                      spec:
                        command: echo hello world
                      timeout: ""
                      type: Run
              platform:
                arch: Amd64
                os: Linux
              runtime:
                spec: {}
                type: Docker
            type: CI
        - stage:
            name: Build
            identifier: Build
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              caching:
                enabled: true
                override: true
              buildIntelligence:
                enabled: true
              platform:
                arch: Amd64
                os: Linux
              runtime:
                spec: {}
                type: Docker
              execution:
                steps:
                  - step:
                      type: BuildAndPushDockerRegistry
                      name: BuildAndPushDockerRegistry_1
                      identifier: BuildAndPushDockerRegistry_1
                      spec:
                        connectorRef: account.harnessImage
                        repo: tabasumkhan534/harness
                        tags:
                          - latest
